# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-12 14:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ligas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('Liga', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ligas.Liga')),
            ],
        ),
    ]
