# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-29 10:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jugadores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tarjetas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tarjetas_amarillas', models.CharField(max_length=1)),
                ('tarjetas_rojas', models.CharField(max_length=1)),
                ('Jugadores', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='jugadores.Jugadores')),
            ],
        ),
    ]
