# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-11 23:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equipos', '0001_initial'),
        ('ligas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='liga',
            name='Equipos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='equipos.Equipos'),
        ),
    ]
