# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-29 10:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tabla',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posicion', models.CharField(max_length=2)),
                ('juegos_jugados', models.CharField(max_length=3)),
                ('juegos_ganados', models.CharField(max_length=3)),
                ('juegos_empatados', models.CharField(max_length=3)),
                ('juegos_perdidos', models.CharField(max_length=3)),
                ('goles_anotados', models.CharField(max_length=2)),
                ('goles_permitidos', models.CharField(max_length=2)),
                ('diferencia_goles', models.CharField(max_length=2)),
                ('puntos', models.CharField(max_length=3)),
                ('Equipos', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='equipos.Equipos')),
            ],
        ),
    ]
